version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aluminate-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - aluminate-network

  backend:
    build:
      context: ./aluminate-global-backend
      dockerfile: Dockerfile
      args:
        GLOBAL_PORT: ${GLOBAL_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_GLOBAL_PRIVATE_KEY: ${SPRING_GLOBAL_PRIVATE_KEY}
      SPRING_ORGANIZATION_PUBLIC_KEY: ${SPRING_ORGANIZATION_PUBLIC_KEY}
      PAYHERE_MERCHANT_SECRET: ${PAYHERE_MERCHANT_SECRET}
      PAYHERE_MERCHANT_ID: ${PAYHERE_MERCHANT_ID}
      API_PREFIX: ${API_PREFIX}
      SRPING_MAIL_HOST: ${SRPING_MAIL_HOST}
      SRPING_MAIL_PORT: ${SRPING_MAIL_PORT}
      SRPING_MAIL_USERNAME: ${SRPING_MAIL_USERNAME}
      SRPING_MAIL_PASSWORD: ${SRPING_MAIL_PASSWORD}
    ports:
      - "${GLOBAL_PORT}:${GLOBAL_PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - aluminate-network

  website-frontend:
    build:
      context: ./aluminate-website-frontend
      dockerfile: Dockerfile
      args:
        WEBSITE_FRONTEND_PORT: ${WEBSITE_FRONTEND_PORT}
        NEXT_PUBLIC_BACKEND_URL: "${DOMAIN_LINK}:${GLOBAL_PORT}${API_PREFIX}"
    ports:
      - "${WEBSITE_FRONTEND_PORT}:${WEBSITE_FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - aluminate-network

  admin-frontend:
    build:
      context: ./aluminate-admin-frontend
      dockerfile: Dockerfile
      args:
        ADMIN_FRONTEND_PORT: ${ADMIN_FRONTEND_PORT}
        NEXT_PUBLIC_BACKEND_URL: "${DOMAIN_LINK}:${GLOBAL_PORT}${API_PREFIX}"
    ports:
      - "${ADMIN_FRONTEND_PORT}:${ADMIN_FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - aluminate-network

volumes:
  postgres_data:

networks:
  aluminate-network:
    external: true
    name: aluminate-global-network
