# Application Configuration
spring.application.name=aluminate-global-backend
server.port=8080

# for local testing on your own local postgres uncomment this
spring.docker.compose.enabled=false

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

# uncomment this for local testing on localhost
# Local testing configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aluminateglobaldb
spring.datasource.username=mario
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging to see table creation
logging.level.org.hibernate.SQL=DEBUG

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration





