# Application Configuration
spring.config.import=optional:configtree:/run/secrets/
spring.application.name=aluminate-global-backend
server.port=${GLOBAL_PORT}

# for local testing on your own local postgres uncomment this
spring.docker.compose.enabled=false

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# uncomment this for local testing on localhost
# Local testing configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/aluminateglobaldb
#spring.datasource.username=senira
#spring.datasource.password=devteam
#spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging to see table creation
logging.level.org.hibernate.SQL=DEBUG

#api prefix
api.prefix=${API_PREFIX}

#Redis
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

#jwt
JWT_SECRET=${JWT_SECRET}

#payhere
payhere.merchant_secret=${PAYHERE_MERCHANT_SECRET}
payhere.merchant_id=${PAYHERE_MERCHANT_ID}

# =============================================
# KAFKA PRODUCER CONFIGURATION
# =============================================

# Bootstrap servers
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# Topic configuration
kafka.topic.global-events=${KAFKA_TOPIC_GLOBAL_EVENTS}

# Serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#keys
encryption.global.private-key=${SPRING_GLOBAL_PRIVATE_KEY}
encryption.organization.public-key=${SPRING_ORGANIZATION_PUBLIC_KEY}

# Reliability settings
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.delivery-timeout-ms=120000
spring.kafka.producer.request-timeout-ms=30000
spring.kafka.producer.max-block-ms=60000

# JSON Serializer specific
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#smtp server configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



