# Application Configuration
spring.application.name=aluminate-global-backend
server.port=8080

# for local testing on your own local postgres uncomment this
spring.docker.compose.enabled=false

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

# uncomment this for local testing on localhost
# Local testing configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aluminateglobaldb
spring.datasource.username=devteam
spring.datasource.password=aluminatedev
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging to see table creation
logging.level.org.hibernate.SQL=DEBUG

#api prefix
api.prefix=/api/v1/global

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#jwt
JWT_SECRET=d9f3a7e2c6b84f9a8d42e1c7f35b0d6e

#payhere
payhere.merchant_secret=MTA2NzYxMjQ3MzE4OTAxNTIyNjYyNDY5NjI2Njk5MzQzNzg2MjE1OQ==
payhere.merchant_id=1229153

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration





